//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrawlerFlight
    {
        public int ID { get; set; }
        public string Airline { get; set; }
        public string AirlineCode { get; set; }
        public Nullable<int> FlightNumber { get; set; }
        public string Aircraft { get; set; }
        public string SourceCity { get; set; }
        public string DestinationCity { get; set; }
        public Nullable<System.DateTime> Departs_at { get; set; }
        public Nullable<System.DateTime> Arrives_at { get; set; }
        public string Duration { get; set; }
        public Nullable<decimal> TicketPrice { get; set; }
    }
}
